
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace StudentInfoModel.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            StudentInfoModel.ModelInput sampleData = new StudentInfoModel.ModelInput()
            {
                Col0 = 14F,
                Col1 = 19F,
                Col2 = 20F,
                Col3 = 8F,
                Col4 = 5F,
                Col5 = 9F,
                Col6 = 5F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = StudentInfoModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Col7 with predicted Col7 from sample data...\n\n");


            Console.WriteLine($"Col0: {14F}");
            Console.WriteLine($"Col1: {19F}");
            Console.WriteLine($"Col2: {20F}");
            Console.WriteLine($"Col3: {8F}");
            Console.WriteLine($"Col4: {5F}");
            Console.WriteLine($"Col5: {9F}");
            Console.WriteLine($"Col6: {5F}");
            Console.WriteLine($"Col7: {1F}");


            Console.WriteLine($"\n\nPredicted Col7: {predictionResult.PredictedLabel}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
